# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-29 08:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=10000)),
                ('author', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('image', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'books',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'genres',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book', models.ForeignKey(blank=True, db_column='book', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Books')),
                ('user', models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_book',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserCommentBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=10000)),
                ('book', models.ForeignKey(blank=True, db_column='book', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Books')),
                ('user', models.ForeignKey(blank=True, db_column='user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_comment_book',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='books',
            name='genre',
            field=models.ForeignKey(blank=True, db_column='genre', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.Genres'),
        ),
    ]
