# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-30 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='rating',
            field=models.FloatField(),
        ),
    ]
