# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-17 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180430_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercommentbook',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
